-- Seig / Leon Flask schema for Supabase PostgreSQL.
-- The Flask app uses its own users table and JWTs; this is not Supabase Auth.
-- Run this in Supabase SQL Editor before setting DATABASE_URL in Flask.

create type public.resume_status as enum ('draft', 'completed', 'archived');

create table public.users (
    id integer generated by default as identity primary key,
    full_name varchar(120) not null,
    email varchar(255) not null unique,
    phone_number varchar(40),
    location varchar(255),
    password_hash varchar(255) not null,
    is_email_verified boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index ix_users_email on public.users (email);

create table public.templates (
    id integer generated by default as identity primary key,
    name varchar(120) not null unique,
    display_name varchar(255) not null,
    template_path varchar(512) not null,
    css_path varchar(512),
    description text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index ix_templates_name on public.templates (name);

create table public.resumes (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    template_id integer references public.templates(id) on delete set null,
    title varchar(255) not null,
    target_role varchar(255),
    professional_summary text,
    linkedin_url varchar(512),
    github_url varchar(512),
    portfolio_url varchar(512),
    website_url varchar(512),
    status public.resume_status not null default 'draft',
    version integer not null default 1 check (version >= 1),
    ats_score double precision,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index ix_resumes_user_id on public.resumes (user_id);
create index ix_resumes_template_id on public.resumes (template_id);
create index ix_resume_user_title on public.resumes (user_id, title);

create table public.experiences (
    id integer generated by default as identity primary key,
    resume_id integer not null references public.resumes(id) on delete cascade,
    company varchar(255) not null,
    job_title varchar(255) not null,
    location varchar(255),
    start_date date,
    end_date date,
    is_current boolean not null default false,
    description text,
    achievements jsonb not null default '{}'::jsonb,
    sort_order integer not null default 0 check (sort_order >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_experiences_date_order check (end_date is null or start_date is null or end_date >= start_date)
);
create index ix_experiences_resume_id on public.experiences (resume_id);
create index ix_experience_resume_sort on public.experiences (resume_id, sort_order);

create table public.educations (
    id integer generated by default as identity primary key,
    resume_id integer not null references public.resumes(id) on delete cascade,
    institution varchar(255) not null,
    degree varchar(255),
    field_of_study varchar(255),
    location varchar(255),
    start_date date,
    end_date date,
    gpa varchar(50),
    description text,
    sort_order integer not null default 0 check (sort_order >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_educations_date_order check (end_date is null or start_date is null or end_date >= start_date)
);
create index ix_educations_resume_id on public.educations (resume_id);
create index ix_education_resume_sort on public.educations (resume_id, sort_order);

create table public.projects (
    id integer generated by default as identity primary key,
    resume_id integer not null references public.resumes(id) on delete cascade,
    name varchar(255) not null,
    description text,
    url varchar(512),
    tech_stack jsonb not null default '{}'::jsonb,
    sort_order integer not null default 0 check (sort_order >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index ix_projects_resume_id on public.projects (resume_id);
create index ix_project_resume_sort on public.projects (resume_id, sort_order);

create table public.skills (
    id integer generated by default as identity primary key,
    resume_id integer not null references public.resumes(id) on delete cascade,
    name varchar(255) not null,
    category varchar(120),
    proficiency varchar(120),
    sort_order integer not null default 0 check (sort_order >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index ix_skills_resume_id on public.skills (resume_id);
create index ix_skill_resume_sort on public.skills (resume_id, sort_order);

create table public.certificates (
    id integer generated by default as identity primary key,
    resume_id integer not null references public.resumes(id) on delete cascade,
    name varchar(255) not null,
    issuer varchar(255),
    issue_date date,
    expiry_date date,
    credential_id varchar(255),
    credential_url varchar(512),
    sort_order integer not null default 0 check (sort_order >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index ix_certificates_resume_id on public.certificates (resume_id);
create index ix_certificate_resume_sort on public.certificates (resume_id, sort_order);

create table public.languages (
    id integer generated by default as identity primary key,
    resume_id integer not null references public.resumes(id) on delete cascade,
    name varchar(120) not null,
    proficiency varchar(120),
    sort_order integer not null default 0 check (sort_order >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index ix_languages_resume_id on public.languages (resume_id);
create index ix_language_resume_sort on public.languages (resume_id, sort_order);

create table public.generated_pdfs (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    resume_id integer not null references public.resumes(id) on delete cascade,
    file_path varchar(512) not null,
    file_name varchar(255) not null,
    file_size integer check (file_size is null or file_size >= 0),
    checksum varchar(128),
    generated_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index ix_generated_pdfs_user_id on public.generated_pdfs (user_id);
create index ix_generated_pdfs_resume_id on public.generated_pdfs (resume_id);
create index ix_generated_pdf_resume_generated on public.generated_pdfs (resume_id, generated_at);

create table public.job_descriptions (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    title varchar(255) not null,
    company varchar(255),
    description text not null,
    source_url varchar(512),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index ix_job_descriptions_user_id on public.job_descriptions (user_id);

create table public.ats_analyses (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    resume_id integer not null references public.resumes(id) on delete cascade,
    job_description_id integer not null references public.job_descriptions(id) on delete cascade,
    score double precision not null,
    matched_keywords jsonb not null default '{}'::jsonb,
    missing_keywords jsonb not null default '{}'::jsonb,
    completeness jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);
create index ix_ats_analyses_user_id on public.ats_analyses (user_id);
create index ix_ats_analyses_resume_id on public.ats_analyses (resume_id);
create index ix_ats_analyses_job_description_id on public.ats_analyses (job_description_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

do $$
declare
    table_name text;
begin
    foreach table_name in array array['users', 'templates', 'resumes', 'experiences', 'educations', 'projects', 'skills', 'certificates', 'languages', 'generated_pdfs', 'job_descriptions']
    loop
        execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()', table_name || '_updated_at', table_name);
    end loop;
end;
$$;

insert into public.templates (name, display_name, template_path, css_path, description)
values
    ('classic', 'Classic', 'classic.html', 'static/css/templates/classic.css', 'A traditional ATS-friendly layout.'),
    ('modern', 'Modern', 'classic.html', 'static/css/templates/modern.css', 'A clean layout with stronger section separation.'),
    ('minimal', 'Minimal', 'classic.html', 'static/css/templates/minimal.css', 'A compact layout that keeps the focus on content.')
on conflict (name) do update set
    display_name = excluded.display_name,
    template_path = excluded.template_path,
    css_path = excluded.css_path,
    description = excluded.description,
    is_active = true,
    updated_at = now();
